### ISSUE TITLE
Sakura_MapStatusHud    If more than 5 people show an error

### ISSUE THREAD

**Issue by gejiziliao** [Sakurano6130/SakuraPlugins#118]
If more than 5 people show an error  ,Cannot read property 'destroy' of null,
You can add input to display several people, or fix multi-person display problems

**Comment by Sakurano6130** [comment]
Thank you, and sorry for the delayed response. I will check this issue.

**Comment by Sakurano6130** [comment]
> If more than 5 people show an error ,Cannot read property 'destroy' of null, You can add input to display several people, or fix multi-person display problems

The following adjustments have been made and released as ver.1.4.0:

Fixed an issue where reserve members would not be displayed if the number of party members exceeded $gameParty.maxBattleMembers.
Thank you for pointing this out.

**Comment by gejiziliao** [comment]
Thank you for the repair. The test was okay




121542650
***@***.***
